kind: Service
apiVersion: v1
metadata:
  name: rocketmq-namesrv-service
  namespace: rocketmq-operator
spec:
  selector:
    app: rocketmq-namesrv
  type: NodePort
  ports:
  - name: port9876
    protocol: TCP
    port: 9876
    targetPort: 9876
    nodePort: 30876
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rocketmq-namesrv
  namespace: rocketmq-operator
  labels:
    app: rocketmq-namesrv
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rocketmq-namesrv
  template:
    metadata:
     labels:
       app: rocketmq-namesrv
    spec:
      containers:
      - name: namesrv
        image: huanwei/rocketmq-namesrv:4.3.0-k8s
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 9876
        volumeMounts:
          - mountPath: /opt/logs
            name: namesrvoptlogs
          - mountPath: /opt/store
            name: namesrvoptstore
      volumes:
      - name: namesrvoptlogs
        hostPath:
          path: /data/namesrv/logs
      - name: namesrvoptstore
        hostPath:
          path: /data/namesrv/store
      nodeSelector:
           rocketmq-operator: "on"
